site_name: JetBot
theme:
    name: "material"
    logo: images/logo.png
    favicon: images/favicon.png
    font: Incosolata
    palette:
        scheme: nvgreen
    features:
       - navigation.expand

repo_url: https://github.com/greennote-inc/jetbot

plugins:
  - search
use_directory_urls: false

edit_uri: blob/master/docs
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
        use_pygments: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list  # for image sizes https://github.com/mkdocs/mkdocs/issues/1678
# use_directory_urls - False to fix broken raw html image links
# https://github.com/mkdocs/mkdocs/issues/991


nav:

  - Home: index.md
  - ALGYAN JetBot:
      - Home: algyan/Home.md
      - Hardware Setup: algyan/Hardware-Setup.md
      - Software Setup: algyan/Software-Setup
  - Greennote AI自動運転カー学習キット:
      - Home: Home.md
      - Hardware Setup: Hardware-Setup.md
      - Software Setup: Software-Setup

extra_css:
  - css/version-select.css
  - css/colors.css
extra_javascript:
  - js/version-select.js
